"""empty message

Revision ID: 833fc01b3573
Revises: 2ac1fc46cdbd
Create Date: 2024-08-08 18:29:59.414553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833fc01b3573'
down_revision = '2ac1fc46cdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
