"""empty message

Revision ID: c870596b6fd2
Revises: e28b33518518
Create Date: 2024-08-10 23:22:55.822182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c870596b6fd2'
down_revision = 'e28b33518518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=250), nullable=False),
    sa.Column('anio_nacimiento', sa.Integer(), nullable=True),
    sa.Column('estatura', sa.Float(), nullable=True),
    sa.Column('color_piel', sa.String(length=250), nullable=True),
    sa.Column('color_cabello', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaje')
    # ### end Alembic commands ###
