"""empty message

Revision ID: e28b33518518
Revises: ba5631a1d56f
Create Date: 2024-08-10 23:11:56.132308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28b33518518'
down_revision = 'ba5631a1d56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_planera', sa.String(length=20), nullable=False),
    sa.Column('clima', sa.String(length=20), nullable=True),
    sa.Column('creacion_planeta', sa.String(length=50), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planeta')
    # ### end Alembic commands ###
